### ISSUE TITLE
ISSUE-7050: [python] pulsar-client@2.5.2's dep on enum34@1.1.9 may break build systems

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1027]
Original Issue: apache/pulsar#7050 

---

Enum34 appears to have had a regression of the below issue in 1.1.9 https://bitbucket.org/stoneleaf/enum34/issues/31/make-the-install-a-noop-on-python36

This breaks builds due to `AttributeError: module 'enum' has no attribute 'IntFlag'`

Related poetry issue: https://github.com/python-poetry/poetry/issues/1122#issuecomment-628037127

Suggest using enum34@1.1.8 until this is fixed

**Comment by curtiscook** [comment]
I think we can close this issue as there is a sufficient workaround
