### ISSUE TITLE
ISSUE-7121: [Documentation] Clarify the impact of batch message in key_shared subscription

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1040]
Original Issue: apache/pulsar#7121 

---

**Is your feature request related to a problem? Please describe.**
Following the java example at http://pulsar.apache.org/docs/en/client-libraries-java/#key_shared. The messages sometimes may send to only one consumer if the producer sends the batched messages. It's better to clarify in the doc to introduce the right way to use key_shared subscription.

**Comment by Huanli-Meng** [comment]
@codelipenghui , how batched messages are dealt in key_shared subscription mode? i am working on fenced messages in Key_shared mode. I am wondering if i can update the key-shared subscription mode contents together.
