### ISSUE TITLE
ISSUE-7312: pulsar-2.6.0 cpp client build error

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1114]
Original Issue: apache/pulsar#7312 

---

**Describe the bug**
build error

**To Reproduce**

[root@VM_72_166_tlinux /data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/build]# cmake ..
-- ARCHITECTURE: x86_64
-- BUILD_TESTS:  ON
-- BUILD_PYTHON_WRAPPER:  ON
-- LINK_STATIC:  OFF
-- USE_LOG4CXX:  OFF
-- CMAKE_BUILD_TYPE:  RelWithDebInfo
-- Found Boost: /usr/local/include (found version "1.54.0") found components: program_options regex system 
-- PYTHON: 2.7.10
-- Found Boost: /usr/local/include (found version "1.54.0") found components: python 
-- HAS_ZSTD: 0
-- HAS_SNAPPY: 1
-- Using Boost Python libs: /usr/local/lib/libboost_python.so
clang-tidy not found
clang-format not found
-- Configuring done
-- Generating done
-- Build files have been written to: /data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/build

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - linux 3.10.106

**Additional context**

/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/CompressionCodecSnappy.cc: In member function 'virtual bool pulsar::CompressionCodecSnappy::decode(const pulsar::SharedBuffer&, uint32_t, pulsar::SharedBuffer&)':
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/CompressionCodecSnappy.cc:43:42: error: cannot convert 'snappy::ByteArraySource*' to 'const char*' for argument '1' to 'bool snappy::Uncompress(const char*, size_t, snappy::string*)'
     if (snappy::Uncompress(&source, &sink)) {
                                          ^
make[2]: *** [lib/CMakeFiles/pulsarShared.dir/CompressionCodecSnappy.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/pulsarShared.dir/all] Error 2

**Comment by firefeifei** [comment]
The above compilation error is required for snappy1.1.8

**Comment by firefeifei** [comment]
`
In file included from /data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/UnboundedBlockingQueue.h:26:0,
                 from /data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/ConsumerImpl.h:25,
                 from /data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/Consumer.cc:21:
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/BlockingQueue.h: In member function 'bool BlockingQueue<T>::tryReserve(size_t)':
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/BlockingQueue.h:77:37: error: there are no arguments to 'assert' that depend on a template parameter, so a declaration of 'assert' must be available [-fpermissive]
         assert(noOfSpots <= maxSize_);
                                     ^
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/BlockingQueue.h:77:37: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/BlockingQueue.h: In member function 'void BlockingQueue<T>::reserve(size_t)':
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/BlockingQueue.h:87:37: error: there are no arguments to 'assert' that depend on a template parameter, so a declaration of 'assert' must be available [-fpermissive]
         assert(noOfSpots <= maxSize_);
                                     ^
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/BlockingQueue.h: In member function 'void BlockingQueue<T>::release(size_t)':
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/BlockingQueue.h:97:43: error: there are no arguments to 'assert' that depend on a template parameter, so a declaration of 'assert' must be available [-fpermissive]
         assert(noOfSpots <= reservedSpots_);
                                           ^
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/BlockingQueue.h: In member function 'void BlockingQueue<T>::push(const T&, BlockingQueue<T>::ReservedSpot&)':
/data/commlibsrc/pulsar-2.6.0/pulsar-client-cpp/lib/BlockingQueue.h:137:34: error: there are no arguments to 'assert' that depend on a template parameter, so a declaration of 'assert' must be available [-fpermissive]
         assert(reservedSpots_ > 0);
                                  ^
make[2]: *** [lib/CMakeFiles/pulsarShared.dir/Consumer.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/pulsarShared.dir/all] Error 2
make: *** [all] Error 2

`
Another compile error

need

#include <assert.h>

**Comment by firefeifei** [comment]
/usr/bin/ld: /usr/local/lib/libsnappy.a(snappy-sinksource.cc.o): relocation R_X86_64_32S against `_ZTVN6snappy6SourceE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libsnappy.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libpulsar.so.2.6.0] Error 1
make[1]: *** [lib/CMakeFiles/pulsarShared.dir/all] Error 2
make: *** [all] Error 2
