### ISSUE TITLE
ISSUE-7415: [Document & Website][Pulsar 2.5.0]--schema registry should be removed from the concept section

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1170]
Original Issue: apache/pulsar#7415 

---

**Describe the bug**

in Pulsar 2.5.0, The schema registry doc under the concept and architecture section as there is a Pulsar schema section

![image](https://user-images.githubusercontent.com/48120384/86242380-39c81c80-bbd7-11ea-999e-26fe0f387031.png)

**Comment by Jennifer88huang** [comment]
@sijia-w could you please fix the issue?

**Comment by sijia-w** [comment]
@Jennifer88huang  When I tried to fix it, I had this problem again.
remote: Permission to apache/pulsar.git denied to sijia-w.
fatal: unable to access 'https://github.com/apache/pulsar/': The requested URL returned error: 403

**Comment by sijia-w** [comment]
@Jennifer88huang  The pr is here https://github.com/apache/pulsar/pull/7590. I will close this issue when it's merged.
