### ISSUE TITLE
ISSUE-4981: [Doc] update config docs

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#12]
Original Issue: apache/pulsar#4981 

---

[Docs](https://pulsar.apache.org/docs/en/reference-configuration/#broker) not up-to-date with [conf](https://github.com/apache/pulsar/blob/branch-2.4/conf/broker.conf)

for example `isSchemaValidationEnforced=false` is not there

**Comment by Jennifer88huang** [comment]
An external contributor is updating the config docs in https://github.com/apache/pulsar/pull/5946
Meanwhile, Jennifer also update some config info for 2.4.x release in https://github.com/apache/pulsar/pull/6047
We need a generator to generate the config info automatically, @tuteng will help on this in https://github.com/apache/pulsar/issues/6048

**Comment by Jennifer88huang** [comment]
@Anonymitaet I've pinged Lidi Wang on this PR, if she could not finish updating the content before Spring Festival, you can ping her or update it after the holiday.
