### ISSUE TITLE
"BadMessageException: 500: No version" Exception In Log

### ISSUE THREAD

**Issue by fantapsody** [streamnative/pulsar#1231]
**Describe the bug**
Seen in broker log:

> 13:05:14.203 [AsyncHttpClient-49-1] ERROR org.glassfish.jersey.server.ServerRuntime$Responder - Error while closing the output stream in order to commit response.
> org.eclipse.jetty.http.BadMessageException: 500: No version
>         at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:391) ~[org.eclipse.jetty-jetty-http-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:743) ~[org.eclipse.jetty-jetty-server-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241) ~[org.eclipse.jetty-jetty-util-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223) ~[org.eclipse.jetty-jetty-util-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:549) ~[org.eclipse.jetty-jetty-server-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:833) ~[org.eclipse.jetty-jetty-server-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:910) ~[org.eclipse.jetty-jetty-server-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:283) ~[org.eclipse.jetty-jetty-server-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:267) ~[org.eclipse.jetty-jetty-server-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:856) ~[org.eclipse.jetty-jetty-server-9.4.29.v20200521.jar:9.4.29.v20200521]
>         at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:325) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.27.jar:?]
>         at java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:167) ~[?:1.8.0_252]
>         at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:302) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:256) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:271) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:848) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:413) ~[org.glassfish.jersey.core-jersey-server-2.27.jar:?]
>         at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:734) ~[org.glassfish.jersey.core-jersey-server-2.27.jar:?]
>         at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395) ~[org.glassfish.jersey.core-jersey-server-2.27.jar:?]
>         at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385) ~[org.glassfish.jersey.core-jersey-server-2.27.jar:?]
>         at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884) ~[org.glassfish.jersey.core-jersey-server-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors.process(Errors.java:268) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916) ~[org.glassfish.jersey.core-jersey-server-2.27.jar:?]
>         at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872) ~[org.glassfish.jersey.core-jersey-server-2.27.jar:?]
>         at org.apache.pulsar.broker.admin.v2.NonPersistentTopics.lambda$getList$1(NonPersistentTopics.java:289) ~[org.apache.pulsar-pulsar-broker-2.6.0-sn-3.jar:2.6.0-sn-3]
>         at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836) ~[?:1.8.0_252]
>         at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811) ~[?:1.8.0_252]
>         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_252]
>         at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_252]
>         at org.apache.pulsar.client.admin.internal.TopicsImpl$5.completed(TopicsImpl.java:222) ~[org.apache.pulsar-pulsar-client-admin-original-2.6.0-sn-3.jar:2.6.0-sn-3]
>         at org.apache.pulsar.client.admin.internal.TopicsImpl$5.completed(TopicsImpl.java:219) ~[org.apache.pulsar-pulsar-client-admin-original-2.6.0-sn-3.jar:2.6.0-sn-3]
>         at org.glassfish.jersey.client.JerseyInvocation$4.completed(JerseyInvocation.java:1015) ~[org.glassfish.jersey.core-jersey-client-2.27.jar:?]
>         at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:227) ~[org.glassfish.jersey.core-jersey-client-2.27.jar:?]
>         at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:85) ~[org.glassfish.jersey.core-jersey-client-2.27.jar:?]
>         at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:178) ~[org.glassfish.jersey.core-jersey-client-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.internal.Errors.process(Errors.java:268) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:312) ~[org.glassfish.jersey.core-jersey-common-2.27.jar:?]
>         at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:178) ~[org.glassfish.jersey.core-jersey-client-2.27.jar:?]
>         at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:208) ~[org.apache.pulsar-pulsar-client-admin-original-2.6.0-sn-3.jar:2.6.0-sn-3]
>         at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[?:1.8.0_252]
>         at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_252]
>         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_252]
>         at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_252]
>         at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:249) ~[org.apache.pulsar-pulsar-client-admin-original-2.6.0-sn-3.jar:2.6.0-sn-3]
>         at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_252]
>         at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_252]
>         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_252]
>         at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_252]
>         at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222) [org.asynchttpclient-async-http-client-2.12.1.jar:?]
>         at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257) [org.asynchttpclient-async-http-client-2.12.1.jar:?]
>         at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241) [org.asynchttpclient-async-http-client-2.12.1.jar:?]
>         at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114) [org.asynchttpclient-async-http-client-2.12.1.jar:?]
>         at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143) [org.asynchttpclient-async-http-client-2.12.1.jar:?]
>         at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78) [org.asynchttpclient-async-http-client-2.12.1.jar:?]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [io.netty-netty-codec-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [io.netty-netty-codec-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [io.netty-netty-codec-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [io.netty-netty-transport-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**To Reproduce**
Not sure, seems to be related with tenant creation:

> ./bin/pulsar-admin namespaces create  public/abc -c neo-1
> 21:06:02.384 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [https://neo-1.matrix.us-west1-a.shared.dev-yyang.g.sn2.dev/admin/v2/namespaces/public/abc] Failed to perform http put request: javax.ws.rs.ServerErrorException: HTTP 504 Gateway Timeout
> HTTP 504 Gateway Timeout
> 
> Reason: HTTP 504 Gateway Timeout

**Desktop (please complete the following information):**
 - OS: OS X

**Comment by sijie** [comment]
@codelipenghui to double-check if he has fixed the problem already.

**Comment by sijie** [comment]
This has been fixed in pulsar 2.6.0-sn-4.
