### ISSUE TITLE
Update Pulsar resource page

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/pulsar#1354]
Some blogs are not added on Pulsar resource page, we can update them accordingly https://pulsar.apache.org/en/resources/

You can find some important blogs on StreamNative website.

**Comment by Jennifer88huang** [comment]
@sijia-w When you finish a task, you can add your PR link here, and move it to "In review" status. You can tag me to review it.

**Comment by sijia-w** [comment]
@Jennifer88huang  Got it. Thanks. The pr is in Pulsar repo. So I should NOT link it here, right? Already tagged you there. Thanks.

**Comment by Jennifer88huang** [comment]
Good job~
