### ISSUE TITLE
ISSUE-7824: JWT token does not expire for opened connections

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1379]
Original Issue: apache/pulsar#7824 

---

#### Expected behavior

I create a consumer listener with Go following an example:

http://pulsar.apache.org/docs/en/client-libraries-go/#consumers

Authentication/Authorisation is done via a JWT token (I provide a function via NewAuthenticationTokenFromSupplier to retrieve this token from Keycloak). The token lifetime is set to 1 minute.

Expected behavior - as soon as token expires a new token should be retrieved (best option) or at least the connection to pulsar brokers should break.

#### Actual behavior

I can still consumer messages with expired token

#### System configuration
**Pulsar version**: 2.6.0

**Comment by zymap** [comment]
Updates: I have been verified both the standalone and cluster mode with the TTL token. All things look good for now. I don't found the issue which is reported. 
I already add a test case for that and the next step will enable cluster mode to test it.
