### ISSUE TITLE
ISSUE-7830: Pulsar Proxy doesn't forward credentials correctly with custom authN/authZ

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1384]
Original Issue: apache/pulsar#7830 

---

**Describe the bug**
When trying to connect to the brokers through the pulsar proxy component using the binary connection the client's `authenticationDataSource` is not being forwarded to the broker for Authorization. When changing the `brokerServiceUrl` to `http://pulsar-proxy:80/` it seems to work with the client credentials but doesn't use the proxy token.

 I've tested this by executing into the toolset container. I've gotten to to work by connecting directly to the broker with the `---url` via the pulsar-client.

**To Reproduce**
1. configure the default helm charts to forward the client creds for the proxy
2. configure a custom authN/authZ within the helm charts
3. put some logs in your authZ methods and print the `AuthenticationDataSource` that is coming into your methods.
4. watch it not work.

**Expected behavior**
I expect the authenticationDataSource for the proxy and the client should be passing through the AuthorizationProvider methods.

**Additional context**
This [thread](https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1597261747377100)

**Comment by Joshhw** [comment]
I believe this is fixed in 2.6.1 from my testing with that version.
