### ISSUE TITLE
ISSUE-7903: AutoTopicCreationType partitioned not supported when passing through proxy

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1411]
Original Issue: apache/pulsar#7903 

---

**Describe the bug**
When auto topic creation type is `partitioned`, the ServerCnx handles get PartitionMetadata by creatiing partitions in `fetchPartitionedTopicMetadataCheckAllowAutoCreationAsync`.

Proxy has other way to handle that and not support the partitioned topics auto creation because it directly answer the current ZK content and not creates partitions.

**Expected behavior**
Broker & Proxy should have the same way to handle auto topic creation.

@codelipenghui I finally get what what's wrong! Can you work on fixing it?

**Comment by zymap** [comment]
There has a PR for adding this. Move to review.
