### ISSUE TITLE
ISSUE-7941: Consumer can't get messages with earliest position subscription type under some circumstances 

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1430]
Original Issue: apache/pulsar#7941 

---

Hello
We have severe issue with partitioned topics and key_shared subscriptions with multiple consumers per subscription.
After some time (could be few hours or few days) the consumers are stopping to consume messages . The backlog continues to grow.

The problem being observed in 2.5.2, 2.6.0, 2.6.1. (we didn't work with earlier versions)

In the broker log we can find these errors:

 [bookkeeper-ml-workers-OrderedExecutor-7-0] WARN  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [persistent://sometenanat/somenamespace/b8d863eb-a632-4ae9-8682-2541f1a9c25e_02bae02b-partition-1][hostidentity-subscription-cloud] Error while replaying entries
org.apache.bookkeeper.mledger.ManagedLedgerException: Unknown exception.

(I am not sure that this error is related to the issue) 

The issue more likely occurs when we do some change in the consumers like remove consumer, add another one.
It seems that it more likely happens with earliest subscription types  .

I see enough available permits, no other problems that can explain this problem.
The problem is very serious and preventing us to move to production.

How can we start to troubleshooting this kind of problem ?

**Comment by alexku7** [comment]
Hello
I am pretty sure that i succeeded to reproduce the conditions for this issue.

create a topic with three partitions. my-tenant/my-namespace/my/topic
The topic should have producers for producing relatively many messages ( let's say 3000 per second) with different keys
create simultaneously 2 consumers with key_shared subscription and earliest position:
bin/pulsar-client consume -p Earliest -n 0 -s alex_test -t Key_Shared persistent://my-tenant/my-namespace/my/topic

3, after 1-2 minutes , create third consumer with the same settings.

You should see after 10-40 seconds that the all partitions are stuck with zero rate out and the backlog continues to grow .

Interesting, that if i remove the third consumer, all are starting working again but if i remove the first or second consumer it's still stuck.

The issue doesn't occur with Latest position.
