### ISSUE TITLE
ISSUE-7960: AuthenticationOAuth2 as Authentication Plugin in Pulsar Proxy

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1438]
Original Issue: apache/pulsar#7960 

---

**Describe the bug**
When setting AuthenticationOAuth2 as brokerClientAuthenticationPlugin the proxy crashes on start-up with an uncaught Exception with message "null".

Relevant config:
brokerClientAuthenticationPlugin=org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
brokerClientAuthenticationParameters={"grant_type": "client_credentials","issuerUrl": "https://example.com/your/auth/url/here","audience": "my_audience", "privateKey": "file:/path/to/keyfile/cc.json"}

The cc.json contains client_id and client_secret as described in the documentation.

**To Reproduce**
1. Set brokerClientAuthenticationPlugin and brokerClientAuthenticationParameters as described seen above.
2. Start the proxy.

**Expected behavior**
The proxy should be able to get a token from our OAuth provider and authenticate itself to the broker.

**Desktop (please complete the following information):**
 - OS: Pulsar is currently running in an kubernetes cluster. We also tried with the standalone version to no avail.

**Additional context**
The broker is defined with the  same config in terms of plugin and authenticationParameters and is able to get a token.

**Comment by EronWright** [comment]
@zymap please add me to the review loop, thanks
