### ISSUE TITLE
Message Expiry for TTL (Time To Live) not working

### ISSUE THREAD

**Issue by kk-0619** [streamnative/pulsar#1442]
Tested with **set-message-ttl** and it is not working. Tried to set TTL expiry time to 10 seconds, 30 seconds, 60 seconds, but the  unacknowledged messages only expires after approximately 4 minutes being sent. Tried to create new namespaces, restart pulsar service, it is still not working.

1. sudo bin/pulsar-admin namespaces set-message-ttl public/test \ --messageTTL 10
2. send unacknowledged message and wait for it to expire.
3. Does not expire based on exact time set.

**Comment by zymap** [comment]
Hi @kk-0619 , did you configure the `messageExpiryCheckIntervalInMinutes` in the broker conf? 
The default value is 5 that means the broker will check the message is expired every 5 minutes.

**Comment by zymap** [comment]
Hi @kk-0619, I will close this issue and feel free to open it again if you have other issues.
