### ISSUE TITLE
ISSUE-8134: [WIP][pulsar-admin-tools] Support delete all data associated with a cluster

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1502]
Original Issue: apache/pulsar#8134 

---

This issue is related to #8133 

- [ ] Add a integration test for deleting cluster's all data and metadata
- [ ] Delete the schema ledgers, see #8136

**Comment by BewareMyPower** [comment]
Close it due to https://github.com/apache/pulsar/pull/8244
