### ISSUE TITLE
ISSUE-8220: managedLedgerOffloadDeletionLagMs and managedLedgerOffloadAutoTriggerSizeThresholdBytes are not used from config file

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1534]
Original Issue: apache/pulsar#8220 

---

**Describe the bug**
Flags `managedLedgerOffloadDeletionLagMs` and `managedLedgerOffloadAutoTriggerSizeThresholdBytes` are not used anywhere so default offloader doesn't pick these values properly and always use defaults null and -1 respectively, even if these flags are set in config file.

**To Reproduce**
Deploy pulsar and set these values in broker.conf file (https://github.com/apache/pulsar/blob/master/conf/broker.conf#L796) to some values different from default, also set offloader settings (https://github.com/apache/pulsar/blob/master/conf/broker.conf#L1054) so it can be tested.
Try to produce data and check if ledgers are being offloaded if u set `managedLedgerOffloadAutoTriggerSizeThresholdBytes` to 0.

**Expected behavior**
Offloader should use values provided from config file.
In my test case if i set `managedLedgerOffloadAutoTriggerSizeThresholdBytes` to 0, offloads should be done immediately after ledger rollover which i inspect with `stats-internal` and ledgers are properly closed. But that don't happen unless i manually set offload threshold with `set-offload-threshold` command from pulsar admin, after that everything work as expected.

**Screenshots**
For above test case, before and after i change offload manually states are: (first ledger is offloaded manually)

<img src="https://user-images.githubusercontent.com/38222386/95482690-b1ec6e00-098e-11eb-8dd6-7760a2260e0f.png" width="300" align="left">
<img src="https://user-images.githubusercontent.com/38222386/95483256-4ce54800-098f-11eb-8395-f038243f86d7.png" width="300">

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
These 2 flags are not read anywhere, in previous implementation they are taken here https://github.com/apache/pulsar/blob/ffe29c30d8963850770f55db86bbcd9ea2f2a095/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1009 but this part is now removed, i think that should be inserted here https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1214.

Also these 2 flags are, in my opinion, more closely part of offloading config instead of managed ledger config, so other solution can be that these 2 parameters are moved in offloader part of configuration and renamed so this function https://github.com/apache/pulsar/blob/ffe29c30d8963850770f55db86bbcd9ea2f2a095/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java#L101 can pick them up properly.

One more thing, values for these 2 flags are stored both in OffloadPolicies class and Policies class (https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/Policies.java#L95), and in Policies class they are not used for anything except for reading that value for pulsar admin get command (https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L2672). And they are set (https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L2699) at the same time so maybe they are redundant and maybe better solution is to move them to offload config and remove them from Policies class.

**Comment by jiazhai** [comment]
https://github.com/apache/pulsar/pull/8310/files

**Comment by jiazhai** [comment]
currently after latest change, has some issue with the ns policy(not able to get right value)

**Comment by jiazhai** [comment]
waiting for test to pass

**Comment by jiazhai** [comment]
Need to build and release a new version of sn customer

**Comment by jiazhai** [comment]
try to release this feature with pulsar 2.6.2
