### ISSUE TITLE
[Doc] Issues on Pulsar Admin API

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1588]
In the sidebar, there are multiple sections "Persistent Topics", "Non-Persistent Topics", "Partitioned Topics" and "Non-Partitioned Topics". I think it is a bit confused. Because persistent topics can be partitioned and non-partitioned.

I think we should refactor this section to have only one section talking about "topics". Also the sub-command `persistent` has been renamed to `topics`. We should change all the occurrences of using `persistent` to using `topics`.

![Screen Shot 2020-10-21 at 2 05 52 PM](https://user-images.githubusercontent.com/1217863/96762731-75197180-13a7-11eb-9001-443feb1c6915.png)
![Screen Shot 2020-10-21 at 2 13 21 PM](https://user-images.githubusercontent.com/1217863/96763566-a4c87980-13a7-11eb-9016-f28f4df65739.png)

**Comment by Jennifer88huang** [comment]
@sijie Except the master branch, which versions do this change apply as well?

**Comment by Jennifer88huang** [comment]
The issue will be fixed in several steps:
- [ ] Merge persistent and non-persistent content in `persistent` file; apachepulsar #8375
- [ ] Merge partitioned and non-partitioned content in `partitioned` file; apachepulsar #8388
- [ ] Merge `persistent` file and `partitioned` file content in `persistent` file.
- [ ] Refine the `persistent` file name and id, remove the unnecessary files, fix links related to those removed files.

**Comment by Jennifer88huang** [comment]
There are some inconsistent opinions on topic resources in REST API. Taking the "REST API in list of topics" as an example. The original one is 
``` {@inject: endpoint|GET|/admin/v2/persistent/:tenant/:namespace|operation/getList}. ```
- according to the issue described above (sijie), We should change all the occurrences of using persistent to using topics, including ones in the REST API. It should be  ``` {@inject: endpoint|GET|/admin/v2/topics/:tenant/:namespace|operation/getList}. ```
- according to Guangning, we can use ":schema" to stand for "persistent" and "non-persistent". It can be refined as ``` {@inject: endpoint|GET|/admin/v2/:schema/:tenant/:namespace|operation/getList}. ```
- according to Yong, we should keep two sets separately for persistent and non-persistent in REST API.
It can be refined as ``` {@inject: endpoint|GET|/admin/v2/persistent/:tenant/:namespace|operation/getList}. ``` and ``` {@inject: endpoint|GET|/admin/v2/non-persistent/:tenant/:namespace|operation/getList}. ```
- I checked the current REST API, and found that we use `persistent` for persistent topics, use `non-persistent` for non-persistent topics.
So which refinement shall we adopt currently?

**Comment by Jennifer88huang** [comment]
I've merged the content from the apachepulsar #8375 and apachepulsar #8388 in one file.
We can address the above issue in the new PR apachepulsar #8462

**Comment by Jennifer88huang** [comment]
Currently, I've adopted the following refinement
Replace "persistent" with "topics" in pulsar-admin and Java, use ":/schema" in REST API.
![image.png](https://images.zenhubusercontent.com/5f4c6f2fcca5766db2ca2634/240f2d69-9491-456b-9916-f57c2bcebdb3)

**Comment by Jennifer88huang** [comment]
Finish them in the following PRs
#8375
#8388
#8462 (fix link issues in the `docs` folder only)
#8481

**Comment by Jennifer88huang** [comment]
@codelipenghui when I tried to use {schema} as variable in the REST API in apachepulsar #8462, and found that the links do not work properly in the `{xxx}` format. So I adopt the `:schema` for them.
The following is the display output with `{schema}` and `:schema` on Pulsar website.
![image.png](https://images.zenhubusercontent.com/5f4c6f2fcca5766db2ca2634/ed00841b-b81d-4acd-9f29-787f8e915944)

**Comment by Jennifer88huang** [comment]
@sijia-w I've finished the updates for the latest version, could you please help adopt the changes in other versions(checking the content in /site2/website/versioned_docs folders)? Thank you very much for doing so.

**Comment by sijia-w** [comment]
@Jennifer88huang Please review pr 8705 in Pulsar repo. Thank you.
