### ISSUE TITLE
ISSUE-4752: [docs] Add Go SerDe option

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#168]
Original Issue: apache/pulsar#4752 

---

**Is your feature request related to a problem? Please describe.**
Currently, Go does not have SerDe option. 

**Describe the solution you'd like**
We can add the option for Go, and complete the content in https://github.com/apache/pulsar/pull/4725.

**Comment by Anonymitaet** [comment]
![image](https://user-images.githubusercontent.com/50226895/86864620-1681fd80-c100-11ea-83fa-066482d2f983.png)
