### ISSUE TITLE
Support Token refresh for Token Provider and client

### ISSUE THREAD

**Issue by jiazhai** [streamnative/pulsar#1687]
In PR https://github.com/apache/pulsar/pull/6074,   feature `Refresh Authentication Credentials` is added, but seems the token auth not implemented it well.

We need to fix the current logic to make the token auth work, and expect that when broker side find the expiration, a new token could get in the client and get authed by broker, so the connection between broker and client will not disconnect.

In `servercnx`, `authState.refreshAuthentication` should detect that the token need a refresh, and send this need-new-token to client side.
```
AuthData brokerData = authState.refreshAuthentication();
ctx.writeAndFlush(Commands.newAuthChallenge(authMethod, brokerData, remoteEndpointProtocolVersion));    
```

In clientCnx, once we get this `need-new-token` auth data, 
```
            AuthData authData = authenticationDataProvider
                .authenticate(AuthData.of(authChallenge.getChallenge().getAuthData().toByteArray()));
```
The provider will request to get a new token, and after that, we start the auth again.

=====

In the broker side, broker will either disconnect the connection (if the client doesn’t support refresh token) or send an auth challenge to client (if the client support refresh token). The client can obtain a new token upon receiving the auth challenge.  This would prevent connection disconnections.

Broker: https://github.com/apache/pulsar/blob/0b041a2af8bdc0340d9d41b301b1ccc973056800/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L638
Client: https://github.com/apache/pulsar/blob/ace3087657d48fe1b44f41a99a016367aa26370a/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L347
https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/AuthenticationDataProvider.java#L142

**Comment by zymap** [comment]
I verified the token refresh with some changes: https://github.com/apache/pulsar/compare/master...zymap:refresh-token

And it seems if we use the supplier to give the token, it will get the token periodically.

And this is the program run video. https://drive.google.com/file/d/1K6gSYAX2hwdAcoaNRhhv0_RZ21YOdlQK/view?usp=sharing

**Comment by zymap** [comment]
I will close this issue for now. Reopen this if needed.
