### ISSUE TITLE
Policy/config to limit the message size at topic level

### ISSUE THREAD

**Issue by syk-coder** [streamnative/pulsar#1723]
**Is your feature request related to a problem? Please describe.**
The current policy to control the size of the message is at the broker level(maxMessageSize). It becomes easier to plan resource quotas for client allocation if the max message size pushed can be given at the topic level.

**Describe the solution you'd like**
A config variable/policy to control the size of the message at the topic level.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 315157973** [comment]
I will work on it
