### ISSUE TITLE
ISSUE-8676: [PIP-50] Package management service implement

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1728]
Original Issue: apache/pulsar#8676 

---

PIP-50 implementation:
- [ ] Introduce the packages management interface API
- [ ] Support bookkeeper storage for the packages management storage
- [ ] Introduce REST APIs for the package management service
- [ ] Add client-side APIs for the package management service
- [ ] Support the package download command in Functions
- [ ] Add document for the package service

PIP: https://github.com/apache/pulsar/wiki/PIP-50%3A-Package-Management

**Comment by zymap** [comment]
The original is closed. Close this as well.
