### ISSUE TITLE
[Placement Policy] Bookie AutoRecovery doesn't respect to ZkIsolatedBookieEnsemblePlacementPolicy

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1838]
**Describe the bug**

When users configure to use `ZkIsolatedBookieEnsemblePlacementPolicy`, it is hard to configure AutoRecovery to respect to the isolation group settings. Because we don't store the isolation group information as part of ledger metadata, the framework doesn't have any information to use for choosing the bookies.

**Expected behavior**

We should be able to configure AutoRecovery to use `ZkIsolatedBookieEnsemblePlacementPolicy`. And it should respect to the isolation group that is assigned to a ledger when recovering it.

**Approach**

1. In ManagedLedger, we need to store the ensemble placement policy properties in the ledger's custom metadata.
2. In ZkIsolatedBookieEnsemblePlacementPolicy, we need to change the implementation of `replaceBookie` to choose a bookie based on the ensemble placement policy properties stored in the ledger's custom metadata.

**Comment by zymap** [comment]
The PR https://github.com/apache/pulsar/pull/8961 for fixing this.
I test this with the bookkeeper configuration https://gist.github.com/zymap/5f0580e44880196ce9ddac31c5f3befe
and setting the ensemble size and write quorum to 2.

The test flow is:
1. setup a cluster with 1 zookeeper, 4 bookkeepers, and 1 broker.
2. make bookies have two groups, group-bookie1, and group-bookie2
3. bind namespace public/usebookie1 to bookie group 'group-bookie1' and namespace public/usebookie2 to bookie group `group-bookie2'
4. publish messages to the topic 'public/usebookie1/topic3'
5. check the ledger is on which bookie
6. decommission one of the bookies which have the ledger
7. check out the ledger is recovered to another bookie in the same group

https://drive.google.com/file/d/1gqmnHMK-3rEGr_uvNhBxaQnVf3NtwCCC/view?usp=sharing

**Comment by zymap** [comment]
https://github.com/apache/pulsar/pull/8961 resolved by this PR.
