### ISSUE TITLE
[Broker] Broker should automatically unload namespace bundles after the isolation policy is changed.

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1839]
**Describe the bug**

The `ns-isolation-policy` take effect for the first time a bundle loaded, which result in several situations after the `ns-isolation-policy` changed:
If all the bundles in a namespace are loaded before the policy change, then that new policy will only take effect after the bundles unload/load again.
If not all the bundles are loaded, then the first time the bundle loaded, the new policy will take effect.

So the easiest way to migrate a namespace from one broker group to another is to unload a namespace after changing the policy.

**Expected behavior**

The isolation policy should take effect immediately after it is changed.

**Comment by jiazhai** [comment]
https://github.com/apache/pulsar/pull/8976/files is for this fix
