### ISSUE TITLE
ISSUE-8977: Add docs of how namespace broker isolation policy works

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1895]
Original Issue: apache/pulsar#8977 

---

currently, there are no enough docs to describe how namespace broker isolation policy works. We need to add some docs for it.
related with PR #8976

**Comment by codelipenghui** [comment]
related to https://docs.google.com/document/d/14dNh4HVgMdlY8oGFSug7qGa4VZnfs-P0veMEeXfS5ac/edit#heading=h.nwa20fmlqo7y

**Comment by Anonymitaet** [comment]
@codelipenghui 

I've drafted one [here](https://docs.google.com/document/d/1GnZQgjhWthTgxBQbFBB-sn4kfiaLtWSg8tTHTaq9Rhg/edit#), could you please help review it overall? (especially for comments) 

Feedback before 1/12 is highly appreciated, thank you~

**Comment by Anonymitaet** [comment]
@codelipenghui many thanks for your guidance!

As we talked just now, we will make the following changes:

- Add detailed and deep descriptions of the feature (for example, the function of each component, how these components work together, etc.) to the "Concept and Architecture" chapter. [Here](https://docs.google.com/document/d/1zEMJDibP5HE9rYa2t0TFm1xrntyx0hJoXgCS7SRzmU0/edit#heading=h.6kwaaatljofh) is the doc structure.

- Add complete practices/tutorial to the "Administration" chapter. [Here](https://docs.google.com/document/d/19fDiYz2oGYNq5F3I30s4s9blREcX5r9mRcsY2qwMxVU/edit#heading=h.n9qicdpi4dr3) is the doc structure.

- Will add internal theory (if needed) in the future.

**Comment by Anonymitaet** [comment]
Hi @codelipenghui, I've updated the [doc](https://docs.google.com/document/d/1zEMJDibP5HE9rYa2t0TFm1xrntyx0hJoXgCS7SRzmU0/edit#), could u PTAL?  
Feedback before 2/8 is highly appreciated, thank you~

**Comment by Anonymitaet** [comment]
@codelipenghui 

This [doc](https://docs.google.com/document/d/1LCIKBraP8S1ZEcwp8WVK2wUP9A54An3rXSKn-T5VNtE/edit#) adds a tech blog to the SN website

This [doc](https://docs.google.com/document/d/16Cr5qsVH3ghCtZaqG_v_PPxV6QEBVp_eY6SCNeIckjw/edit#) adds guides to the Pulsar website

Could you please check overall and answer the questions in these docs? 

Feedback before 2/21 is highly appreciated, thank you~

**Comment by Anonymitaet** [comment]
@codelipenghui 

Could you please take a quick look at these two docs?

This [doc](https://docs.google.com/document/d/1LCIKBraP8S1ZEcwp8WVK2wUP9A54An3rXSKn-T5VNtE/edit#) adds a tech blog to the SN website, could you please provide simple commands?

This [doc](https://docs.google.com/document/d/16Cr5qsVH3ghCtZaqG_v_PPxV6QEBVp_eY6SCNeIckjw/edit#) adds guides to the Pulsar website

Feedback before 2/25 is highly appreciated, thank you~

**Comment by Anonymitaet** [comment]
@codelipenghui I’ve submitted a PR for Pulsar doc, PTAL: https://github.com/apache/pulsar/pull/9692

**Comment by Anonymitaet** [comment]
@Jennifer88huang @Huanli-Meng could you please help review [Taking an in-depth look at how to achieve isolation in Pulsar](https://docs.google.com/document/d/1LCIKBraP8S1ZEcwp8WVK2wUP9A54An3rXSKn-T5VNtE/edit#)? Thanks
