### ISSUE TITLE
[docs] Add Haskell client content for Pulsar docs

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/pulsar#1922]
See http://pulsar.apache.org/docs/en/client-libraries/
Links are added, yet the detailed content is not added. Add similar content with that for other clients (e.g.: Java, Python...)

**Comment by Anonymitaet** [comment]
Confirmed w/ @codelipenghu, I need to ask the author if he'd like to donate the project to Pulsar, if yes, then I will work on the docs. Otherwise, the priority of this task is low.

I've sent an email and a tweet msg to the author. Waiting for his feedback.

**Comment by Anonymitaet** [comment]
The author would like to donate the Haskell client to Pulsar. WIP: https://github.com/apache/pulsar/issues/9076

**Comment by Anonymitaet** [comment]
![image.png](https://images.zenhubusercontent.com/5fd87a84b9bf7aad279b0809/595f2168-ee0e-4639-a951-c7dc1dac38f1)
