### ISSUE TITLE
ISSUE-9051: [Doc] ProtobufNative Schema Support

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1937]
Original Issue: apache/pulsar#9051 

---

Add doc based on https://github.com/apache/pulsar/pull/8372

**Comment by Anonymitaet** [comment]
hi @congbobo184 

I've documented my thoughts [here](https://docs.google.com/document/d/1fzgAfqtw5U9yrbff0Nboq2WHw4-57dNZ5JAy843oCG4/edit#), could you please help answer the questions? 

Any suggestions and feedback b4 12/30 are highly appreciated. Many thanks

**Comment by Anonymitaet** [comment]
https://github.com/apache/pulsar/pull/9079
