### ISSUE TITLE
ISSUE-9168: What's the batch Delay default value

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#1993]
Original Issue: apache/pulsar#9168 

---

![image](https://user-images.githubusercontent.com/12933197/104148191-3fb37b80-540c-11eb-817d-03ae94602ebf.png)
In this annotation, the default value is 10 ms.
But in this code, the default value is 1.
![image](https://user-images.githubusercontent.com/12933197/104148219-6376c180-540c-11eb-9b5b-da5367b9e5d8.png)

Which value is recommended? It seems scheduly task execs per 1 ms easily cause the application OOM

**Comment by Jennifer88huang** [comment]
When I search the issue "set the time period within which the messages sent will be batched", I found that if we change the value, the following files are affected (as well as the go.md file in sn-platform), see screenshot below.
![image](https://user-images.githubusercontent.com/47805623/104285803-1a4b6e00-54ef-11eb-86ad-64a151ad65a4.png)

**Comment by Jennifer88huang** [comment]
@sijia-w  The comment in the code and the documentation should all be changed into `1ms`.
