### ISSUE TITLE
ISSUE-9216: Support get topic applied policy

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#2019]
Original Issue: apache/pulsar#9216 

---

**Is your feature request related to a problem? Please describe.**
Provide a way to get the applied policy of the topic. In Pulsar, the topic will apply the topic level policy if present or apply the namespace policy if present or use the broker level configuration. It needs to support get the applied policy for a topic that might use the namespace policy or topic policy or broker level default configuration. 

**Describe the solution you'd like**
Add "--applied" for the get policy cmd. For example:

```
bin/pulsar-admin topics get-retention --applied
```

- [ ]   1. MessageTTL
- [ ]   2. Retention Policy
- [ ]   3. Message Dispatch Rate
- [ ]   4. Backlog Quota
- [ ]   5. Persistence Policy
- [ ]   6. Max Producer
- [ ]   7. Max Consumer
- [ ]   8. Compaction Threshold
- [ ]   9. Deduplication
- [ ]   10. Offload Policy
- [ ]   11. MaxUnackMessagesPerConsumer
- [ ]   12. MaxUnackMessagesPerSubscription
- [ ]   13. DelayedDeliveryPolicies
- [ ]   14. Inactive topic policy

**Comment by Jennifer88huang** [comment]
@codelipenghui The command/description and usage are generated automatically on [Pulsar CLI website](https://pulsar.apache.org/pulsar-admin-cli/?version=2.7.0), so we don't need to add the content manually now.
Yu Liu will track the final status on the Pulsar website after generation.
