### ISSUE TITLE
ISSUE-9285: Flink source connector can not use the same client config with sink connector.

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#2050]
Original Issue: apache/pulsar#9285 

---

**Describe the bug**
When I pass the same ClientConfigurationData object to source and sink.  The source connector will not recive data any more.
When I use different ClientConfigurationData object for source and sink, all works normally.

The same issue exists in both io.streamnative.connectors:pulsar-flink-connector  and  org.apache.pulsar:pulsar-flink .

**To Reproduce**
pass the same ClientConfigurationData object to source and sink

**Expected behavior**
source and sink works.

**Desktop (please complete the following information):**
 - pulsar 2.7.0
 - flink 1.12

**Comment by codelipenghui** [comment]
@jianyun8023 Is it related to this fix https://github.com/apache/pulsar/pull/8980 that you pushed out?

**Comment by jianyun8023** [comment]
> @jianyun8023 Is it related to this fix [apache#8980](https://github.com/apache/pulsar/pull/8980) that you pushed out?

There is no connection. But I will test to verify that the connector has no such problem.
