### ISSUE TITLE
ISSUE-9327: Retry and Dead letter topics are generated with wrong names when retry is enabled

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#2061]
Original Issue: apache/pulsar#9327 

---

**Describe the bug**

Currently RetryLetter and DeadLetter topics names only depend on subscription name and not on the topic name (so there is a clash when different consumers work with different topics and same subscription name)
[Link](https://github.com/apache/pulsar/blob/branch-2.7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java#L123-L124)

There is a [duplicate code block](https://github.com/apache/pulsar/blob/branch-2.7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L325-L344) where topic names are generated correctly, but those are not in use since policy is generated at builder time.

Issue exists for both 2.6 and 2.7 branches

**To Reproduce**
1. Setup 2 consumers that listen to different topics, but the same subscription name
2. Enable retry for both
3. See that retry and dead letter generated topics are the same, so there is a messages clash

**Expected behavior**
Generated topics should be based both on topic name and subscription name (like [here](https://github.com/apache/pulsar/blob/branch-2.7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L335))

**Comment by mingyifei** [comment]
java```
if(conf.isRetryEnable() && conf.getTopicNames().size() > 0 ) {
            TopicName topicFirst = TopicName.get(conf.getTopicNames().iterator().next());
            String retryLetterTopic = topicFirst + "-" + conf.getSubscriptionName() + RetryMessageUtil.RETRY_GROUP_TOPIC_SUFFIX;
            String deadLetterTopic = topicFirst + "-" + conf.getSubscriptionName() + RetryMessageUtil.DLQ_GROUP_TOPIC_SUFFIX;

            //Issue 9327: do compatibility check in case of the default retry and dead letter topic name changed
            String oldRetryLetterTopic = topicFirst.getNamespace() + "/" + conf.getSubscriptionName() + RetryMessageUtil.RETRY_GROUP_TOPIC_SUFFIX;
            String oldDeadLetterTopic = topicFirst.getNamespace() + "/" + conf.getSubscriptionName() + RetryMessageUtil.DLQ_GROUP_TOPIC_SUFFIX;
            try {
                if (client.getPartitionedTopicMetadata(oldRetryLetterTopic)
                        .get(client.conf.getOperationTimeoutMs(), TimeUnit.MILLISECONDS).partitions > 0) {
                    retryLetterTopic = oldRetryLetterTopic;
                }
                if (client.getPartitionedTopicMetadata(oldDeadLetterTopic)
                        .get(client.conf.getOperationTimeoutMs(), TimeUnit.MILLISECONDS).partitions > 0) {
                    deadLetterTopic = oldDeadLetterTopic;
                }
            } catch (InterruptedException | TimeoutException e) {
                return FutureUtil.failedFuture(e);
            } catch (ExecutionException e) {
                return FutureUtil.failedFuture(e.getCause());
            }

            if(conf.getDeadLetterPolicy() == null) {
                conf.setDeadLetterPolicy(DeadLetterPolicy.builder()
                                        .maxRedeliverCount(RetryMessageUtil.MAX_RECONSUMETIMES)
                                        .retryLetterTopic(retryLetterTopic)
                                        .deadLetterTopic(deadLetterTopic)
                                        .build());
            } else {
                if (StringUtils.isBlank(conf.getDeadLetterPolicy().getRetryLetterTopic())) {
                    conf.getDeadLetterPolicy().setRetryLetterTopic(retryLetterTopic);
                }
                if (StringUtils.isBlank(conf.getDeadLetterPolicy().getDeadLetterTopic())) {
                    conf.getDeadLetterPolicy().setDeadLetterTopic(deadLetterTopic);
                }
            }
            conf.getTopicNames().add(conf.getDeadLetterPolicy().getRetryLetterTopic());
        }
```

Why can query the number of partitions be resolved?

**Comment by mingyifei** [comment]
If multiple topics use the same subscription name, and the number of partitions between oldRetryLetterTopic and oldDeadLetterTopic> 0, can the problem be solved?  @sijie

**Comment by mingyifei** [comment]
**What is wrong with deleting the red box code?**

![image](https://user-images.githubusercontent.com/38995810/147437746-66cf63f9-c8f9-49c7-a8d0-1b6a7b6d6476.png)

**Comment by mingyifei** [comment]
@sijie
