### ISSUE TITLE
Provide the storage size metric for offloaded and non-offloaded data

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#2063]
*Problem*

Currently, we only expose one storage size metric that includes both offloaded and non-offloaded data. We should probably provide two more metrics, one of offloaded data, and the other one for non-offloaded data.

**Comment by codelipenghui** [comment]
@sijie Since we already have the total storage size, is it better to only expose one metrics such as offloaded storage size, so that we can get the non-offloaded data from `total-storage-size - offloaded-storage-size`.

**Comment by sijie** [comment]
@codelipenghui That works for me.

**Comment by zymap** [comment]
PR for this. https://github.com/apache/pulsar/pull/9335

**Comment by zymap** [comment]
PR merged. Close this issue.
