### ISSUE TITLE
ISSUE-4898: Update Functions state documentation for Python

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#212]
Original Issue: apache/pulsar#4898 

---

Pulsar Functions documentation at http://pulsar.apache.org/docs/en/functions-state/ needs to be updated to note that Python functions support state, and to provide examples of how to use state with Python.

**Comment by Jennifer88huang** [comment]
It's fixed in the latest doc http://pulsar.apache.org/docs/en/next/functions-develop/#state-storage
