### ISSUE TITLE
ISSUE-9597: Add api to delete retained message for a topic

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#2169]
Original Issue: apache/pulsar#9597 

---

**Is your enhancement request related to a problem? Please describe.**
When retention policies are applied on a topic. Messages acknowledged for all subscription are kept on topic storage because of retention policies. 

At time we are required to clear up all data from topic storage. 

**Describe the solution you'd like**
There should be an api, which allow api user to delete all acknowledged message from topic storage.

**Describe alternatives you've considered**
NA

**Additional context**
Below storage size contains the message retained on topic due to retention policies. These messages were already consumed by subscribers.  We need a way to delete these messages only. while keep the topic around.

<img width="1833" alt="Screenshot 2021-02-16 at 4 41 24 PM" src="https://user-images.githubusercontent.com/6093884/108056964-fba13f80-7077-11eb-9a54-6ea99ac3885f.png">

**Comment by vlad-rosu** [comment]
Same problem. From prometheus side, the `pulsar_storage_size` keeps increasing even though messages have been acknowledged. (retention policy was present and the `pulsar_storage_size` wasn't decreasing)

**Comment by sijie** [comment]
@vlad-rosu If you have a retention policy enabled, the acknowledged messages will be kept around. You can watch this video to understand the difference between storage size and backlog. https://www.youtube.com/watch?v=PIX570nyq_c&list=PLqRma1oIkcWhWAhKgImEeRiQi5vMlqTc-&index=6
