### ISSUE TITLE
ISSUE-10355: [Blog] announce Pulsar 2.7.2

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#2437]
Original Issue: apache/pulsar#10355 

---

Hi @eolivelli 

I see you are cutting the 2.7.2 release, thanks for your great effort!

To announce the new release officially, would you like to write a blog for 2.7.2 as we did before? After that, I can help review.

In this blog, I suggest highlighting major enhancements/bug fixes and adding necessary explanations for them instead of putting every enhancement/bug fix in it. In this way, users can catch up the points quickly rather than being overwhelmed by information. If they want to know the complete list, they can check the release note.

FYI: you can take the [previous release blogs ](https://pulsar.apache.org/blog/) as references.

Any thoughts on this?

**Comment by eolivelli** [comment]
Sure. I will be happy to do it
