### ISSUE TITLE
ISSUE-5459: macOS 10.15 support

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#245]
Original Issue: apache/pulsar#5459 

---

**Describe the bug**
pip install pulsar-client==2.4.1 on macOS 10.15 results in:
ImportError: dlopen(/Users/ericnielson/venv/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf-lite.20.dylib
  Referenced from: /Users/ericnielson/venv/lib/python3.7/site-packages/_pulsar.cpython-37m-darwin.so
  Reason: image not found

**To Reproduce**
1. on macOS 10.15 $ pip install pulsar-client==2.4.1
2. Write .py with "import pulsar"
3. Try to run 

**Expected behavior**
i would expect this to run

output from pip install:
ericnielson:~ ericnielson$ pip install pulsar-client==2.4.1
Requirement already satisfied: pulsar-client==2.4.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2.4.1)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pulsar-client==2.4.1) (2018.11.29)
Requirement already satisfied: protobuf>=3.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pulsar-client==2.4.1) (3.10.0)
Requirement already satisfied: prometheus-client in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pulsar-client==2.4.1) (0.7.1)
Requirement already satisfied: six in ./Library/Python/3.7/lib/python/site-packages (from pulsar-client==2.4.1) (1.11.0)
Requirement already satisfied: apache-bookkeeper-client>=4.9.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pulsar-client==2.4.1) (4.9.2)
Requirement already satisfied: grpcio in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pulsar-client==2.4.1) (1.18.0)
Requirement already satisfied: ratelimit in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pulsar-client==2.4.1) (2.2.1)
Requirement already satisfied: fastavro in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pulsar-client==2.4.1) (0.22.5)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from protobuf>=3.6.1->pulsar-client==2.4.1) (40.6.2)
Requirement already satisfied: pytz in ./Library/Python/3.7/lib/python/site-packages (from apache-bookkeeper-client>=4.9.2->pulsar-client==2.4.1) (2018.9)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in ./Library/Python/3.7/lib/python/site-packages (from apache-bookkeeper-client>=4.9.2->pulsar-client==2.4.1) (2.22.0)
Requirement already satisfied: pymmh3>=0.0.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from apache-bookkeeper-client>=4.9.2->pulsar-client==2.4.1) (0.0.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->apache-bookkeeper-client>=4.9.2->pulsar-client==2.4.1) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->apache-bookkeeper-client>=4.9.2->pulsar-client==2.4.1) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./Library/Python/3.7/lib/python/site-packages (from requests<3.0.0dev,>=2.18.0->apache-bookkeeper-client>=4.9.2->pulsar-client==2.4.1) (2.7)

**Comment by hozn** [comment]
Appears to still be happening with 2.5.0.  Actually, I'm still on 10.14.3 and seeing this same error.
