### ISSUE TITLE
ISSUE-3104: [Feature request] Namespace/topic rack affinity

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#279]
Original Issue: apache/pulsar#3104 

---

When deploying a single cluster over multiple AZ/regions, one of the main drawbacks is the cross-dc bandwidth used by the producers/consumers.
So it would be handy to be able to configure rack affinity either of namespaces or topics so that the brokers are chosen in priority on the preferred rack with fallback on other racks if no brokers are available on the preferred rack.

**Comment by Huanli-Meng** [comment]
Will update the current docs and ask for more inputs if required.

**Comment by Huanli-Meng** [comment]
need the input for namespace isolation, mainly include two parts:

what is namespace isolation.
how to use the namespace isolation.
