### ISSUE TITLE
中国地震局台网 Customer tracking

### ISSUE THREAD

**Issue by congbobo184** [streamnative/pulsar#2817]
https://drive.google.com/drive/u/1/folders/1uwnKPQvunjUgD3AvPL9RwR5km4msmvrS

**Comment by congbobo184** [comment]
1.已经搭建由3台物理机组成的Pulsar集群
2.Telnet connector开发完毕
3.方健提出寻找虚拟机为何搭建集群失败的原因。

**Comment by codelipenghui** [comment]
@congbobo184 Could you please provide the result for the task?
