### ISSUE TITLE
ISSUE-4550: Dashboard shows data only after running pulsar-admin command (docker, standalone)

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#290]
Original Issue: apache/pulsar#4550 

---

**Describe the bug**
I am using docker-compose to run pulsar in standalone mode together with dashboard. However, my dashboard stays empty until I run `bin/pulsar-admin clusters list` inside the pulsar container.

**To Reproduce**
1. Create docker-compose.yaml
```
# docker-compose.yaml
version: "3.7"
services:
  apache-pulsar:
    hostname: apache-pulsar
    image: apachepulsar/pulsar:2.3.2
    command: ["bin/pulsar", "standalone"]
    ports:
      - "6650:6650"
      - "8080:8080"
  apache-pulsar-dashboard:
    hostname: apache-pulsar-dashboard
    image: apachepulsar/pulsar-dashboard
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://apache-pulsar:8080
```

2. Run `docker-compose up`
3. Go to `http://locahost` and check the dashboard. It does not show data.
4. Run `docker exec apache-pulsar /bin/bash`
5. Run `bin/pulsar-admin cluster list` inside the container
6. The dashboard now shows data (might need a refresh).

**Expected behavior**
Have the dashboard show data without running a command in the container.

**Desktop (please complete the following information):**
 - OS: macOS but running in docker containers

**Additional context**
Might be related to #3367

**Comment by laninog** [comment]
You should add _advertisedAddress_ parameter to command:

```
apache-pulsar:
    image: apachepulsar/pulsar
    command: ["bin/pulsar", "standalone", **"--advertised-address", "apache-pulsar"**]
    ports:
      - "6650:6650"
...
```

This way, Dashboard service can reach the correct host inside Docker. It worked for me.
