### ISSUE TITLE
Topic-level backlog quota and policy - not working as expected

### ISSUE THREAD

**Issue by disserakt** [streamnative/pulsar#2913]
Hi to all!
This issues based on a slack thread: https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1626704395027300

Our installation Pulsar and Bookkeeper is on LXC containers. Pulsar version for now 2.7.2

When I tried to set the quota backlog at the topic level or get them on our Pulsar product cluster, I got this error(for example with such a request: `curl -L http://pulsar03:8080/admin/v2/persistent/public/default/perf_client_perf_queue_3/backlogQuotaMap`):

```
--- An unexpected error occurred in the server ---

Message: Topic policies cache have not init. 
```

But I found such a pattern - when there are active producers or consumers, you cannot set backlog quotas or retention for a topic level. But if the topic does not have producers or consumers, then you can.

We have partitioned topics in cluster. And if a partitioned topic has active producers and consumers - or there are only active producers, but no active consumers - then when i set (or get) backlog quotas or retention at the topic level, an error occurs.
When there are no active clients for a topic - then everything is successful.

But this behavior was fixed in the next issues, related to `”Topic policy cache not init”`

https://github.com/apache/pulsar/pull/11136
https://github.com/apache/pulsar/pull/11097
https://github.com/apache/pulsar/pull/11003
https://github.com/apache/pulsar/pull/10957
https://github.com/apache/pulsar/pull/10941

And on tip from @sijie  I checked it out on weekly releases, including those fixes.
I have used the following docker images:

```
streamnative/pulsar-all:2.7.2.8
streamnative/pulsar-all:2.7.2.9
streamnative/pulsar-all:2.7.2.10
```
And in these versions everything works as it should - when setting `set-backlog-quota `and `set-retention `for any of the topics with active clients (I used 10 partitioned topics with 6 partitions and launched a load of about `25K RPM for each topic` - the same load for publishing and consuming) - everything works as it should.

Then we made a load of about `330K RPM for publishing` and the `220К RPM  for consuming` for cluster. `33K and 22K RPM` per topic - so that the topics have a backlog.
And as a result, the policies set for the backlog quotas at the topic level did not work. 
For example - I put a backlog-quota limit on a topic of 40MB and retention policy - `producer_exception`
But the producer did not give an error - when the backlog, like for the entire topic first, and then for separately for each partition, exceeded 40MB.

I checked it by looking at the result of the command:
`./pulsar-admin topics partitioned-stats persistent://public/default/perf_client_perf_queue_6 --per-partition `
and the metric `backlogSize`. Based on its values, I saw that the backlog limit was exceeded.

Stats for the whole topic: https://slack-files.com/T5Z3B324U-F02AFLKGU9W-c0c4e5bba6
And per partitions (when they have not reached the quota limit): https://slack-files.com/T5Z3B324U-F029P0Y3NPP-5cf0f50ade
And per partitions (when they exceeded the quota limit): https://slack-files.com/T5Z3B324U-F029S26U50A-8c9d0071dc

Backlog quota and retention for this topic:
```
root@broker2:/pulsar/bin# ./pulsar-admin topics get-backlog-quotas persistent://public/default/perf_client_perf_queue_6
"destination_storage  BacklogQuota{limit=41943040, policy=producer_exception}"
```
```
root@broker2:/pulsar/bin# ./pulsar-admin topics get-retention persistent://public/default/perf_client_perf_queue_6
{
 "retentionTimeInMinutes" : 14400,
 "retentionSizeInMB" : 27648
}

```
I also set the backlog quota at the namespace level - and it worked as expected. I set the retention policy also to `producer_exception ` And when the size of the backlog of the topic partitions reached the value of the backlog quota that I set at the namespace level - the producers gave a write exception and stopped his work.

As a result of this testing, I opened this issue to fix the behavior of the backlog quota at the topic level.

**To Reproduce**
1. Run Pulsar cluster from docker image `streamnative/pulsar-all:2.7.2.X`
2. Make such a load on the cluster so that the topics have a backlog.
3. Set the backlog quota at the topic level, for example `./pulsar-admin topics set-backlog-quota persistent://public/default/perf_client_perf_queue_9 --limit 55M --policy producer_exception`
4. See that topic-level backlog quota didn't work

**Expected behavior**
Topic-level quota backlog works as expected - set retention policies are triggered on clients appropriate behavior.

**Desktop:**
 - OS: MacOS

**Server where docker containers were running:**
 - OS: Debian

**Comment by codelipenghui** [comment]
@disserakt Have you tried 2.7.3? We have lots of fixes related to the topic policy in 2.7.3

**Comment by disserakt** [comment]
@codelipenghui - not yet. But are there any changes in `2.7.3` that are not in `streamnative/pulsar-all:2.7.2.10`?
`2.7.2.10` was released later and judging by the changelog, they are the same.

**Comment by gaoran10** [comment]
I make a test for backlog quota in Pulsar `streamnative/pulsar-all:2.7.2.10 `.

1. namespace retention
```
➜  apache-pulsar-2.7.2.10 bin/pulsar-admin namespaces get-retention public/default
Warning: Nashorn engine is planned to be removed from a future JDK release
{
  "retentionTimeInMinutes" : 1440,
  "retentionSizeInMB" : 500
}
```

2. namespace backlog quota
```
➜  apache-pulsar-2.7.2.10 bin/pulsar-admin namespaces get-backlog-quotas public/default
Warning: Nashorn engine is planned to be removed from a future JDK release
"destination_storage    BacklogQuota{limit=10737418240, policy=producer_request_hold}"
```

3. topic backlog quota
```
➜  apache-pulsar-2.7.2.10 bin/pulsar-admin topics get-backlog-quotas t1
Warning: Nashorn engine is planned to be removed from a future JDK release
"destination_storage    BacklogQuota{limit=10485760, policy=producer_exception}"
```

4. add subscription and prepare data for topic `t1`

5. check topic stats
```
➜  apache-pulsar-2.7.2.10 bin/pulsar-admin topics stats t1
Warning: Nashorn engine is planned to be removed from a future JDK release
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 0.0,
  "msgThroughputOut" : 0.0,
  "bytesInCounter" : 13090902,
  "msgInCounter" : 12152,
  "bytesOutCounter" : 0,
  "msgOutCounter" : 0,
  "averageMsgSize" : 0.0,
  "msgChunkPublished" : false,
  "storageSize" : 13090902,
  "backlogSize" : 13069362,
  "offloadedStorageSize" : 0,
  "publishers" : [ ],
  "subscriptions" : {
    "sub" : {
      "msgRateOut" : 0.0,
      "msgThroughputOut" : 0.0,
      "bytesOutCounter" : 0,
      "msgOutCounter" : 0,
      "msgRateRedeliver" : 0.0,
      "chuckedMessageRate" : 0,
      "msgBacklog" : 12126,
      "backlogSize" : 0,
      "msgBacklogNoDelayed" : 12126,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "type" : "Exclusive",
      "msgRateExpired" : 0.0,
      "totalMsgExpired" : 0,
      "lastExpireTimestamp" : 0,
      "lastConsumedFlowTimestamp" : 1630480273247,
      "lastConsumedTimestamp" : 0,
      "lastAckedTimestamp" : 0,
      "lastMarkDeleteAdvancedTimestamp" : 1630480285794,
      "consumers" : [ ],
      "isDurable" : true,
      "isReplicated" : false,
      "consumersAfterMarkDeletePosition" : { },
      "nonContiguousDeletedMessagesRanges" : 0,
      "nonContiguousDeletedMessagesRangesSerializedSize" : 0
    }
  },
  "replication" : { },
  "deduplicationStatus" : "Disabled",
  "nonContiguousDeletedMessagesRanges" : 0,
  "nonContiguousDeletedMessagesRangesSerializedSize" : 0
}
```

6. found pulsar-perf tool error
```
15:14:05.230 [pulsar-client-io-2-1] WARN  org.apache.pulsar.testclient.PerformanceProducer - Write error on message
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$ProducerBlockedQuotaExceededException: The backlog quota of the topic t1 that the producer standalone-0-3 produces to is exceeded
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:777) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) [?:?]
	at org.apache.pulsar.client.impl.ProducerImpl$1.sendComplete(ProducerImpl.java:307) [io.streamnative-pulsar-client-original-2.7.2.10.jar:2.7.2.10]
	at org.apache.pulsar.client.impl.ProducerImpl$OpSendMsg.sendComplete(ProducerImpl.java:1201) [io.streamnative-pulsar-client-original-2.7.2.10.jar:2.7.2.10]
	at org.apache.pulsar.client.impl.ProducerImpl.lambda$failPendingMessages$20(ProducerImpl.java:1585) [io.streamnative-pulsar-client-original-2.7.2.10.jar:2.7.2.10]
	at java.util.concurrent.ArrayBlockingQueue.forEach(ArrayBlockingQueue.java:1456) [?:?]
	at org.apache.pulsar.client.impl.ProducerImpl.failPendingMessages(ProducerImpl.java:1575) [io.streamnative-pulsar-client-original-2.7.2.10.jar:2.7.2.10]
	at org.apache.pulsar.client.impl.ProducerImpl.lambda$failPendingMessages$21(ProducerImpl.java:1607) [io.streamnative-pulsar-client-original-2.7.2.10.jar:2.7.2.10]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) [io.netty-netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by gaoran10** [comment]
The partitioned named topic couldn't get the topic level policies. The PR https://github.com/apache/pulsar/pull/11294 already fix this problem, we need to cherry-pick this PR to the Pulsar branch `branch-2.7`.

**Comment by gaoran10** [comment]
Add a PR https://github.com/apache/pulsar/pull/11897 for branch-2.7.

**Comment by disserakt** [comment]
@gaoran10 - Hi, Thank you very much! I am very glad that we managed to find and fix this error. It turns out that the matter was in the type of topic, the fact that it is partitioned.

How, after fixing this error, will I need to refer to the partitioned topic in order to set or get a backlog quota - by the name of the entire topic or by the name of the partition?

And I’ll be sure to check out the latest weekly build  `streamnative/pulsar-all:2.8.0.X` soon to see how the topic-level policy backlog works there.
