### ISSUE TITLE
ISSUE-12224: Partitions rebalance listener for Consumer

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#3105]
Original Issue: apache/pulsar#12224 

---

When using processors with in-memory state, it's important to know the partitions assigned and de-assigned. This allows to load and unload the state, and to recover based from a durable eventually consistent snapshot by loading it based on these partitions.

At the moment, you can try to derive this information from the Message IDs, but there are 2 problems with this approach.

1. You don't know when a partition is de-assigned for a Consumer. This forces you to use a time-based cache eviction policy.
2. When you recover from a crash, you don't know the whole set of partitions assigned, meaning you're forced to load from durable storage the state for each partition when you encounter it in a MessageID. This means a less efficient startup.

Ideally, you should expose something like the [ConsumerRebalanceListener](https://kafka.apache.org/30/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html) in Kafka.

**Comment by RagingKore** [comment]
Hi, I'm currently facing this problem when trying to do full blown processing. 

Without being able to finish any ongoing work and then acknowledging the processed messages or perhaps dropping them, the next consumer instance will start executing these same messages.
