### ISSUE TITLE
ISSUE-5552: [Pulsar Functions] Allowed to subscribe from an arbitrary point in time 

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#340]
Original Issue: apache/pulsar#5552 

---

**Is your feature request related to a problem? Please describe.**

In some times, user wants a specific subscription-position for input-topic consumer in Pulsar Functions.

**Describe the solution you'd like**

- Add `SubscriptionInitialPosition` param in create consumer for input topics.

**Comment by wolfstudy** [comment]
https://github.com/apache/pulsar/issues/6531
