### ISSUE TITLE
ISSUE-5399: Create documentation for KubernetesSecretsTokenAuthProvider

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#35]
Original Issue: apache/pulsar#5399 

---

Currently, the `KubernetesSecretsTokenAuthProvider` used by the K8S runtime is not documented at all. This should be documented along with details of how it works and the new functionality to add the CA as well

**Comment by Jennifer88huang** [comment]
An external contributor said he would work on this.

**Comment by sijie** [comment]
@Jennifer88huang Can you work with @addisonj on this task?

**Comment by Jennifer88huang** [comment]
@addisonj please help review updates in https://github.com/apache/pulsar/pull/7806
Any comment is highly appreciated.
