### ISSUE TITLE
ISSUE-4585: [spark streaming] support spark structured streaming 

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#352]
Original Issue: apache/pulsar#4585 

---

Spark structured streaming is the latest program mode of spark streaming, see https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html

**Comment by ivyy** [comment]
when will this feature be integrated into pulsar and become officially just like spark&kafka?

**Comment by sijie** [comment]
@ivyy you can checkout the pulsar-spark connector here: https://github.com/streamnative/pulsar-spark

We will push the connector to the upstream Spark. but it is totally up to Spark community whether it will accept Pulsar connector.
