### ISSUE TITLE
ISSUE-14436: [Proto] java.lang.IllegalStateException: Some required fields are missing

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#3812]
Original Issue: apache/pulsar#14436 

---

**Describe the bug**
![image](https://user-images.githubusercontent.com/39078850/155444823-a7283952-bc22-49e7-99b3-8b2df6a8f7f4.png)
parse message metadata throw Exception
**To Reproduce**
1. start up a standalone pulsar, the version is bigger than 2.10.0
2. change broker config 
transactionCoordinatorEnabled=true
managedLedgerMaxEntriesPerLedger=3
managedLedgerMinLedgerRolloverTimeMinutes=1
3. config namespace ttl ./pulsar-admin namespaces set-message-ttl -ttl 10  public/default
4. ``` 
        PulsarClient pulsarClient = PulsarClient.builder().enableTransaction(true).serviceUrl("pulsar://127.0.0.1:6650").build();
        int sendTopicsCount = 200;
        String topicName = "test55";
        List<Producer<String>> producers = new ArrayList<>(sendTopicsCount);

        for (int i = 0; i < sendTopicsCount; i++) {
            producers.add(pulsarClient.newProducer(Schema.STRING).sendTimeout(0, TimeUnit.SECONDS).topic(i + topicName).create());
             Consumer<String> consumer = pulsarClient.newConsumer(Schema.STRING).subscriptionName("test").topic(i + topicName).subscribe();
            consumer.closeAsync();
        }
        for (int j = 0; j < 10000; j ++) {
            for (int i = 0; i < sendTopicsCount; i++) {
                Transaction transaction = pulsarClient.newTransaction()
                        .withTransactionTimeout(10, TimeUnit.SECONDS).build().get();
                System.out.println("send one transaction messageId" + producers.get(i)
                        .newMessage(transaction).value(i + topicName).send() + "   topic name : " + i);
                transaction.commit();
                Thread.sleep(10);
            }
        }```
Execute the above code multiple times
Execute `./pulsar-admin namespaces unload public/default` multiple times during execute the above code
![image](https://user-images.githubusercontent.com/39078850/155444823-a7283952-bc22-49e7-99b3-8b2df6a8f7f4.png)
**Expected behavior**
can't throw exception

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Not a stable reproduction, requires multiple trials

**Comment by codelipenghui** [comment]
https://github.com/apache/bookkeeper/pull/3110 has fixed the issue. Need to cut a new bookkeeper release and bump bookkeeper dependency to the new bookkeeper release
