### ISSUE TITLE
ISSUE-14642: [Feature] Support reader interceptor

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#3891]
Original Issue: apache/pulsar#14642 

---

**Is your feature request related to a problem? Please describe.**
In [PIP 23](https://github.com/apache/pulsar/wiki/PIP-23%3A-Message-Tracing-By-Interceptors), pulsar has supported producer interceptor and consumer interceptor, but we don't have reader interceptor for now.

To support reader interceptor will allow users to do integration with Pulsar client.

**Describe the solution you'd like**
Introduce a new ReaderInterceptor interface to intercept message before read operation

**Comment by gaoran10** [comment]
The PR https://github.com/apache/pulsar/pull/14729 will support the reader interceptor feature.
