### ISSUE TITLE
ISSUE-2793: TLS Hostname verification undefined for C++/python client

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#400]
Original Issue: apache/pulsar#2793 

---

I've not tested with code, but it looks like TLS hostname verification is a mess for the C++ client (and python by extension).

For binary connections, no hostname verification takes place as far as I can see. For http connections (for lookups) it takes place every time.

I suspect this made it through testing since the tls certs used to test C++ use localhost as the common name. We should expose the ability to add the host verification in the configuration.

**Comment by Huanli-Meng** [comment]
need a host verification code example through python client.

**Comment by Huanli-Meng** [comment]
Doc is updated, here is the doc PR: https://github.com/apache/pulsar/pull/7162

doc is updated for the master currently. after it is reviewed and approved, will update it to previous releases (until 2.3.0).

**Comment by Huanli-Meng** [comment]
Docs for Pulsar releases: master--2.2.0 are merged. I think this issue can be closed.
