### ISSUE TITLE
ISSUE-16596: Broker: add metrics about server-side filtering (PIP-105)

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#4549]
Original Issue: apache/pulsar#16596 

---

**Is your enhancement request related to a problem? Please describe.**
I would like to see a metric about the outcomes of filters:
- number of messages passes thru the filter
- number of accepted messages
- number of rejected messages
- number of rescheduled messages

This must be per-subscription

**Additional context**
This is useful to estimate how many messages are filtered out by a subscription filter

**Comment by tjiuming** [comment]
https://github.com/apache/pulsar/pull/16932
