### ISSUE TITLE
ISSUE-3224: Function option --subscription-type does not work

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#456]
Original Issue: apache/pulsar#3224 

---

The option is documented at https://pulsar.apache.org/docs/en/pulsar-admin/#create-1, but it is actually an invalid option. I find it was once supported in the CmdFunctions.java source code but was deleted later. Will it be supported again?

#### System configuration
**Pulsar version**: 2.2.0

**Comment by Huanli-Meng** [comment]
in code subscription-type for functions is removed since 2.1.0 release. but docs in releases 2.2.0, 2.3.0 and 2.3.1 are not updated. other releases have been updated.
https://github.com/apache/pulsar/pull/7386

**Comment by Huanli-Meng** [comment]
The doc is updated and i think the issue can be closed.
