### ISSUE TITLE
ISSUE-5157: [docs] How does --processing-guarantees affect source connectors?

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#486]
Original Issue: apache/pulsar#5157 

---

The command `sources create` accepts a `--processing-guarantees` option. I tried to find out what's the difference between the accepted options but I could not find an answer in the docs.

Did I miss something or does the documentation need a little improvement?

Thank you!

**Comment by Antti-Kaikkonen** [comment]
I'm trying to figure out how to implement effectively once processing guarantees in a source connector. 

Should it work if I implement [getRecordSequence](http://pulsar.apache.org/api/pulsar-functions/org/apache/pulsar/functions/api/Record.html)? I'm thinking that this way pulsar could discard duplicates with the same sequence, but I don't see this implemented in any of the build in source connectors.

**Comment by Anonymitaet** [comment]
![image](https://user-images.githubusercontent.com/50226895/87494156-e64ad980-c680-11ea-8b92-6d79baf4b564.png)

**Comment by Jennifer88huang** [comment]
@sijia-w please help fix this issue, thank you.

**Comment by Jennifer88huang** [comment]
Check and review in https://github.com/apache/pulsar/pull/7767
