### ISSUE TITLE
Add missing doc for features released in 2.4.0

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/pulsar#548]

**Comment by sijie** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [ISSUE-5959: [doc] Client Features Matrix - To be Updated to 2.4.2 #521](https://github.com/streamnative/pulsar/issues/521)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/FHTn/issues/10656535) | N/A | tuteng | Untriaged | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by Anonymitaet** [comment]
Done
