### ISSUE TITLE
[docs] Breakdown tasks for missing docs for 2.4.0 release

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/pulsar#556]
Create related tasks and provide enough and clear info on how to fix.

**Comment by Jennifer88huang** [comment]
Shall we add those tasks in apache/pulsar repo, or in streamnative/pulsar repo?
If I report some issues in the apache/pulsar repo, and add related labels (help wanted), external contributors can also participate in; add label (triage/week-xx), it will aslo be copied to streamnative/pulsar repo?

**Comment by Jennifer88huang** [comment]
Add those tasks in apache/pulsar repo

**Comment by Jennifer88huang** [comment]
Transfer this task to @Anonymitaet, she will deal with the remaining tasks in the google sheet.

**Comment by Anonymitaet** [comment]
https://docs.google.com/spreadsheets/d/1ktb9IQ8_qqSgLoJ_bCFpG0TFjw-CGqGdpVekJzUE3eU/edit#gid=317905639
