### ISSUE TITLE
ISSUE-6084: [v2.5.0] Functions dead-letter-topic parameter not supported

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#583]
Original Issue: apache/pulsar#6084 

---

**Describe the bug**
In the Functions reference https://pulsar.apache.org/docs/en/functions-cli/ it shows a parameter `dead-letter-topic`. When using it, it is passed to `/pulsar/instances/python-instance/python_instance_main.py` under the `--function_details` json as
```
"customRuntimeOptions": "persistent://tenant/namespace/dlq-topic"
```
But `customRuntimeOptions` is not recognized:
```
google.protobuf.json_format.ParseError: Message type "proto.FunctionDetails" has no field named "customRuntimeOptions".
 Available Fields(except extensions): ['tenant', 'namespace', 'name', 'className', 'logTopic', 'processingGuarantees', 'userConfig', 'secretsMap', 'runtime', 'autoAck', 'parallelism', 'source', 'sink', 'resources', 'packageUrl', 'retryDetails', 'runtimeFlags', 'componentType']
```

**To Reproduce**
1. Create pulsar function with `--dead-letter-topic` argument

**Expected behavior**
Function should be configured correctly

**Desktop (please complete the following information):**
 - OS: Docker

**Additional context**
pulsar tag v2.5.0

**Comment by jiazhai** [comment]
Need to add doc for python function not support dead-letter-topic parameter

**Comment by Huanli-Meng** [comment]
Proposed doc updates：
Pulsar: Pulsar Functions> Reference CLI> localrun/create/update:

Add a note in the dead-letter-topic in Pulsar Functions> Reference CLI> localrun/create/update to indicate dead letter topic is not supported in Python functions.

https://pulsar.apache.org/docs/en/functions-cli/#localrun

**Comment by Huanli-Meng** [comment]
the doc is updated and under review, here is the PR link: https://github.com/apache/pulsar/pull/6980

**Comment by Huanli-Meng** [comment]
the doc is updated and under review, here is the PR link: https://github.com/apache/pulsar/pull/6980

**Comment by Huanli-Meng** [comment]
the doc PR is approved.

**Comment by Huanli-Meng** [comment]
The doc PR is merged.
