### ISSUE TITLE
ISSUE-6087: [docs] Document for delete inactive topic when subscriptions caught up

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#586]
Original Issue: apache/pulsar#6087 

---

This issue tracks the document for delete inactive topic when subscriptions caught up(#6077)

**Comment by Huanli-Meng** [comment]
The doc is updated and under review, here is the PR link: https://github.com/streamnative/streamnative-docs/pull/169

**Comment by Huanli-Meng** [comment]
doc update for SN platform is reviewed and merged. here is the PR link: https://github.com/streamnative/streamnative-docs/pull/169
doc for updated for Pulsar is added based on doc updated for SN platform. No more review is needed. Here is the PR link: https://github.com/apache/pulsar/pull/6990

**Comment by Huanli-Meng** [comment]
doc for SN is approved and merged.

Doc for Pulsar is approved but not merged.

**Comment by Huanli-Meng** [comment]
docs for Pulsar have been merged.
