### ISSUE TITLE
ISSUE-6109: [doc][suggest]  Tell user the available values of "--sink-type" parameter

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#595]
Original Issue: apache/pulsar#6109 

---

**Is your feature request related to a problem? Please describe.**
Tell user the available values of "--sink-type" parameter.

**Describe the solution you'd like**
When i create a Cassandra sink like this.
```bash
bin/pulsar-admin sinks create \
    --tenant public \
    --namespace default \
    --name cassandra-test-sink \
    --sink-type cassandra \
    --sink-config-file examples/cassandra-sink.yml \
    --inputs test_cassandra

```
I could't understand,  Why is the value of  "--sink-type" parameter cassandra ,And when i create the other sinks,  What value should be set for this parameter.

**Describe alternatives you've considered**
Provide a available values list  for this parameter.

**Additional context**

**Comment by Huanli-Meng** [comment]
doc is updated: https://github.com/apache/pulsar/pull/7699 for master
