### ISSUE TITLE
ISSUE-6116: Download page has multiple entries for some artifacts

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#600]
Original Issue: apache/pulsar#6116 

---

The download page has separate entries for "Flume sink" and "Flume source", however these link to identical downloads.

This is confusing and could lead to someone downloading both.

Why not combine the two as "Flume source and sink"?
Similarly for the other duplicates on the page.

**Comment by sijia-w** [comment]
@sijie 1. Is it necessary to combine the download link for source and sink? 
2. Should it be updated to be consistent with these two pages http://pulsar.apache.org/docs/en/io-connectors/ and http://pulsar.apache.org/docs/en/io-cdc/ ? 
3. Should it be placed in alphabetical order?

**Comment by sijie** [comment]
@sijia-w 

1. if the package is identical, we need to combine it.
2. yes.
3. ideally yes.

**Comment by sijia-w** [comment]
https://github.com/apache/pulsar/pull/7472
