### ISSUE TITLE
ISSUE-6117: FlinkPulsarProducer: Setting topic dynamically based on message content

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#601]
Original Issue: apache/pulsar#6117 

---

While using FlinkPulsarProducer we need to set topic dynamically based on the message content.

In FlinkKafkaProducer, the sink topic can be set dynamically by overriding getTargetTopic method in KeyedSerializationSchema. FlinkPulsarProducer uses SerializationSchema, PulsarKeyExtractor is used to extract key from the message. How can we change the sink topic based on message content in case of FlinkPulsarProducer?

**Comment by parth-sarathy** [comment]
We are enhancing our application to use Pulsar instead of Kafka as message bus. So I raised this issue as Enhancement Request (to prevent loss of the dynamically setting sink topic functionality, after porting the application to use Pulsar).
