### ISSUE TITLE
ISSUE-6215: [Python Function] localrun deployment cannot store state 

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#645]
Original Issue: apache/pulsar#6215 

---

**Updated description**
When deploying a localrun python pulsar function i can never store any state successfully over the context object in the pulsar function. After i store some key, value using context.put_state(key=key, value=value) the context.get_state(...) method always returns None!

If i deploy the same function using "create" instead of "localrun" 
the storage of state works fine.

**To Reproduce**
I use version 2.5.0 of the pulsar docker container.
If i deploy the function in the pulsar container, i ll use the pulsar-admin cli like this:
```
/pulsar/bin/pulsar-admin functions localrun \
--broker-service-url pulsar://broker_container:6650 \
--tenant user1 \
--namespace namespace1 \
--py /pulsar_functions/function1.py \
--name function_test \
--user-config '{"output_topic": "persistent://user1/namespace1/output_topic"}' \
--classname function1.Function1 \
--custom-serde-inputs '{"persistent://user1/namespace1/input_topic1":"function1.MyJsonSerDe"}' \
```
I noticed that the input msgs from the broker_container topic are indeed arriving in the function 
and the process hook function gets triggered, but the state never gets stored.

Did i forget to specify something? (like state-storage-service-url?)

**Expected behavior**
Be able to store and retrieve state from the context object no matter if the function is deployed
as "localrun" or with "create".

**Comment by SaturnIC** [comment]
Thank you for mentioning the issue,
please note the changes i made to the original issue,
since i found out that all the problems are solely due to the "localrun" deployment,
using "create" instead resolves all the issues.

**Comment by SaturnIC** [comment]
I found the solution, the problem was indeed the --broker-service-url flag.
I found the solution looking at the pulsar logs during function creation when using "create":
--state_storage_serviceurl bk://127.0.0.1:4181

This service url must be added manually when deploying a localrun function.

There is no example or hint about this issue anywhere in the documentary so i suggest
to add this information to the documentary.

It is no bug.

**Comment by Huanli-Meng** [comment]
docs have been updated for pulsar releases: master, 2.5.2--2.3.0.
releases 2.6.0 and 2.6.1 are not updated because as Jennifer suggested to add tags for 2.6.0 and 2.6.1 for cherry-pic.

no need to update SN doc.

here is the PR link: https://github.com/apache/pulsar/pull/7411
