### ISSUE TITLE
ISSUE-6282: [Doc] Update registry doc (client)

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#680]
Original Issue: apache/pulsar#6282 

---

![image](https://user-images.githubusercontent.com/50226895/74149679-4ad1ba80-4c43-11ea-9c89-b1b1c4a3a11e.png)

**Comment by Huanli-Meng** [comment]
doc is updated for the master, and here is the PR: https://github.com/apache/pulsar/pull/7137

once the update is reviewed and approved, documents in previous releases will be updated.

**Comment by Huanli-Meng** [comment]
docs for 2.5.2--2.5.0: https://github.com/apache/pulsar/pull/7191
