### ISSUE TITLE
ISSUE-6327: The pulsar-perf generated HdrHistogram file open failed

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#705]
Original Issue: apache/pulsar#6327 

---

**Describe the bug**
Use pulsar-perf to start to publish messages and generate HdrHistogram file, when to open the file by https://hdrhistogram.github.io/HdrHistogram/plotFiles.html. The error occurs.
![image](https://user-images.githubusercontent.com/12592133/74520278-2d0d9980-4f52-11ea-9f1f-ed6ac59dfc78.png)

**Comment by Huanli-Meng** [comment]
Add docs for both SN and pulsar:
SN doc PR: https://github.com/streamnative/streamnative-docs/pull/163
Pulsar doc PR: https://github.com/apache/pulsar/pull/6970
