### ISSUE TITLE
ISSUE-6518: health monitoring, alarms

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#795]
Original Issue: apache/pulsar#6518 

---

**Is your feature request related to a problem? Please describe.**

There is apache pulsar [deploy-monitoring article](https://pulsar.apache.org/docs/en/deploy-monitoring/#__docusaurus), it describes how to to collect metrics.

These are exposes metrics (via prometheus endpoint)

> https://github.com/apache/pulsar/blob/master/site2/docs/reference-metrics.md

Most of them are performance metrics, it is very nice to have them but it is **not clear how to monitor health status of the broker, what alarm rules should we apply**.

___

**Describe the solution you'd like**

There is `CockroachDB` monitoring documtetaion:

> https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html#events-to-alert-on

It is `monitoring-and-alerting` and it has `events-to-alert-on` part, which is very helpful.

> Most of them are performance metrics

This is question for devs, probably pulsar should expose some health metrics (errors, etc) in addition.

Are there any internal health metrics that can be added?

Any suggestions about `events-to-alert-on`?

___

**Additional context**

**Comment by Jennifer88huang** [comment]
@sijie Then shall we add alert example or other examples to Pulsar docs?

**Comment by Jennifer88huang** [comment]
https://github.com/apache/pulsar/pull/7342
