### ISSUE TITLE
ISSUE-6519: Functions runtime support consume messages asynchronously

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#797]
Original Issue: apache/pulsar#6519 

---

Functions runtime does not allow to consume messages asynchronously. Async communication is needed when a message processing requires communication with external system.

**Comment by sijie** [comment]
```
CompletableFuture<R> apply (T input);
```

**Comment by jiazhai** [comment]
> ```
> CompletableFuture<R> apply (T input);
> ```

@sijie  AFAIK, if this is the requirement, the only benefit, which user can get,  is handling input message async, and may brings better performance.
 
Not get the point: 
> Async communication is needed when a message processing requires communication with external system.
Would you please help explain a little?

**Comment by sijie** [comment]
The application might use RPCs to call external systems.

**Comment by jiazhai** [comment]
I see. it would be like this?
```
    CompletableFuture<R> apply (T input) {
        CompletableFuture future = new CompletableFuture();
        ...function compute...
        future.whenComplete(() -> {
            ...  call external system  ...
        });
        return future;
    }

```
