### ISSUE TITLE
ISSUE-6520: Provide support to configure different docker images for java function

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#799]
Original Issue: apache/pulsar#6520 

---

Provide support to configure different docker images for go, python, java function

**Comment by wolfstudy** [comment]
Currently, k8s runtime uses a separate image, as follows:

```
  functions:
    repository: streamnative/platform
    tag: v1.0.0
```

We need to provide different image for go, java and python language separately.

**Comment by jiazhai** [comment]
go: 
python:

**Comment by wolfstudy** [comment]
https://hub.docker.com/repository/docker/streamnative/python-functions

**Comment by sijie** [comment]
@wolfstudy I would actually suggest naming them as:

- `java-function-runner` for running java functions
- `python-function-runner` for running python functions
