### ISSUE TITLE
ISSUE-6724: Compile client failed with container

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#879]
Original Issue: apache/pulsar#6724 

---

**Describe the bug**
When i try to compile client with container,  it failed with link error.

/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-CentOS-linux/4.8.2/ld: /usr/local/lib/libsnappy.a(snappy.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

In the container, i find the snappy compiled with  CFLAGS="-fPIC -O3" .
# Snappy
RUN curl -O -L https://github.com/google/snappy/releases/download/1.1.3/snappy-1.1.3.tar.gz && \
    tar xvfz snappy-1.1.3.tar.gz && \
    cd snappy-1.1.3 && \
    CFLAGS="-fPIC -O3" ./configure && \
    make && make install && \
    rm -rf /snappy-1.1.3 /snappy-1.1.3.tar.gz

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by wenxuwan** [comment]
Hi, for snappy the flag should be CXXFLAGS="-fPIC -O3" instead of CFLAGS="-fPIC -O3".After replacement, the compilation is normal
