### ISSUE TITLE
ISSUE-6748: `pulsar.broker-service-url` is misleading in presto configuration

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#885]
Original Issue: apache/pulsar#6748 

---

*Motivation*

`pulsar.broker-service-url` in presto configuration is misleading. The name seems to indicate that you should use a broker service URL. But actually it is expecting the admin/HTTP service URL. So it is better to add a new `pulsar.admin-service-url` to replace this `pulsar.broker-service-url` setting.

At least, we need to document this setting.

**Comment by Jennifer88huang** [comment]
an external contributor is fixing this in https://github.com/apache/pulsar/pull/6757/

**Comment by Jennifer88huang** [comment]
Is there solution to fix the CI tests? The PR is blocked with CI tests.

**Comment by Jennifer88huang** [comment]
It's blocked by CI test. 
Will check all similar PRs after the CI works well.
