### ISSUE TITLE
ISSUE-6832: Cannot connect to multiple geo-replicated partitioned topics via consumer

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#919]
Original Issue: apache/pulsar#6832 

---

We are using the geo-repliated model, producing in US-East via a partitioned topic (persistent://my-tenant/my-namespace/my-topic). Looking in US-West, we can see persistent://my-tenant/my-namespace/my-topic-part0 to part2, as expected. Problem is that when we try to connect to persistent://my-tenant/my-namespace/my-topic in US-West or to 
persistent://my-tenant/my-namespace/my-topic.* via regex, the java consumer client does not get any messages produces in US-East via persistent://my-tenant/my-namespace/my-topic or persistent://my-tenant/my-namespace/my-topic-partition-.* .

I have read the documentation multiple times and no real success to consume a geo-replicated partitioned topic. Only way o can consume is manually consuming from persistent://my-tenant/my-namespace/my-topic-partition-0 (not a multi topic).

Thanks for your help.

**Comment by darksungg** [comment]
Adding to this it seems that testing the issue, having 3 consumers on 1 client for each partition does not work, the second consumer gets stuck at .subscribe().

I've tried via the tutorial and it did not work possible the above problem (gets stuck at subscribe() also)

ConsumerBuilder consumerBuilder = pulsarClient.newConsumer()
.subscriptionName(subscription);

// Subscribe to all topics in a namespace
Pattern allTopicsInNamespace = Pattern.compile("persistent://public/default/.*");
Consumer allTopicsConsumer = consumerBuilder
.topicsPattern(allTopicsInNamespace)
.subscribe();
