### ISSUE TITLE
ISSUE-6841: autoSkipNonRecoverableData does not work when use reader.seek

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#927]
Original Issue: apache/pulsar#6841 

---

**Describe the bug**
when reading data from pulsar, if  autoSkipNonRecoverableData is set, then the reading process will not block due to certain NonRecoverableLedgerException. However, when use Reader API and use seek(timestamp) method, this configuration takes no effect.
**To Reproduce**

**Expected behavior**
Seek should not fail due to certain NonRecoverableLedgerException

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jiazhai** [comment]
There seems also another similar issue for skip Non Recoverable Data on SchemaLedger
