### ISSUE TITLE
ISSUE-6884: Pulsar SQL not returning latest row

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#947]
Original Issue: apache/pulsar#6884 

---

**Describe the bug**
As titled, running query on Pulsar SQL, and it doesn't return the last row of the topic

**To Reproduce**
 For example a topic has 0 row, then I add one row by publishing a message (aaa) to pulsar server. I query the table selecting *, it shows 0 rows. Then i publish another message (bbb), and try to query select * again, row "aaa" shows up, but not "bbb", if i publish another message (ccc), and then query, 2 rows returned: "aaa", "bbb"

**Expected behavior**
All the rows to show after the query

**Additional context**
Running on Pulsar 2.4.2
Also as someone is facing issue in 2.5.0
https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1588064084428500

**Comment by codelipenghui** [comment]
close via https://github.com/apache/pulsar/issues/6884
