### ISSUE TITLE
ISSUE-6898: [document] document  for Pulsar Function worker metrics.

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#955]
Original Issue: apache/pulsar#6898 

---

**Is your feature request related to a problem? Please describe.**
Currently, we have documents for broker, bookie, and zookeeper under https://pulsar.apache.org/docs/en/2.5.1/reference-metrics/#__docusaurus. But there is no document for Pulsar Function worker metrics.

**Comment by Anonymitaet** [comment]
long has provided some metrics here: https://docs.google.com/document/d/1JJl5gSHuF-rhG1TuGGMY46ZGZZ9nb7f90m7S_cEN8hs/edit, he will add more
