### ISSUE TITLE
ISSUE-6897: [document] document for Pulsar SQL worker metrics.

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#957]
Original Issue: apache/pulsar#6897 

---

**Is your feature request related to a problem? Please describe.**
Currently, we have documents for broker, bookie, and zookeeper under https://pulsar.apache.org/docs/en/2.5.1/reference-metrics/#__docusaurus. But there is no document for Pulsar SQL metrics.

**Comment by wolfstudy** [comment]
https://github.com/apache/pulsar/pull/7031
https://github.com/streamnative/streamnative-docs/pull/176
