### ISSUE TITLE
ISSUE-6927: Add C# client documentation

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar#974]
Original Issue: apache/pulsar#6927 

---

**Is your feature request related to a problem? Please describe.**
Since we have official c# client https://github.com/apache/pulsar-dotpulsar, we'd better add the C# client documentation in the client documentation. 

![image](https://user-images.githubusercontent.com/12592133/81468880-b8768e00-9214-11ea-9ef3-97562a05366b.png)

**Comment by sijie** [comment]
@Huanli-Meng : https://github.com/apache/pulsar-dotpulsar/wiki

**Comment by Huanli-Meng** [comment]
docs may be impacted:
Get-started> Use Pulsar with client libraries
- add a bullet for C#
- update feature matrix list (need help)
Security: add contents about C#
- Transport encryption using TLS
- authentication using TLS
- authentication using JWT
Client libraries
-C#: a new doc for the C# client

**Comment by Huanli-Meng** [comment]
doc is drafted. here is the PR link: https://github.com/apache/pulsar/pull/7003

**Comment by Huanli-Meng** [comment]
The doc PR is merged and I think the issue can be closed.

**Comment by Huanli-Meng** [comment]
docs have been updated for SN, here is the PR link: https://github.com/streamnative/streamnative-docs/pull/174

**Comment by Huanli-Meng** [comment]
The doc is updated and the pr is merged so i think this issue can close.
